language: bash

os:
  - osx

osx_image: xcode9.4

addons:
  homebrew:
    update: true

matrix:
    include:
    - env: ARCH=--build-all-x86
    - env: ARCH=--build-all-x64

script:
    - bash ./macos-build.sh $ARCH

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "build/devilutionX.dmg"
  skip_cleanup: true
  on:
    tags: true
