version: 2
jobs:
  linux_x86_64:
    docker:
      - image: debian:stretch-backports
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y cmake g++ libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev
      - run: apt-get install -y -t stretch-backports libsodium-dev
      - run: mkdir build
      - run: cd build && cmake ..
      - run: cd build && make -j$(nproc)
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_linux_x86_64}
  linux_x86:
    docker:
      - image: debian:stretch-backports
    working_directory: ~/repo
    steps:
      - checkout
      - run: dpkg --add-architecture i386
      - run: apt-get update -y
      - run: apt-get install -y cmake g++-multilib libsdl2-dev:i386 libsdl2-mixer-dev:i386 libsdl2-ttf-dev:i386 libsodium-dev
      - run: apt-get install -y -t stretch-backports libsodium-dev:i386
      - run: mkdir build
      - run: cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../CMake/32bit.cmake ..
      - run: cd build && make -j$(nproc)
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_linux_x86}
  windows_x86:
    docker:
      - image: debian:stretch-backports
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y gcc-mingw-w64-i686 g++-mingw-w64-i686 wget
      - run: apt-get install -y -t stretch-backports cmake
      - run: wget https://www.libsdl.org/release/SDL2-devel-2.0.9-mingw.tar.gz
      - run: tar -xzf SDL2-devel-2.0.9-mingw.tar.gz
      - run: wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-mingw.tar.gz
      - run: tar -xzf SDL2_ttf-devel-2.0.15-mingw.tar.gz
      - run: wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-mingw.tar.gz
      - run: tar -xzf SDL2_mixer-devel-2.0.4-mingw.tar.gz
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.17-mingw.tar.gz
      - run: tar -xzf libsodium-1.0.17-mingw.tar.gz --no-same-owner
      - run: cp -r libsodium-win32/* /usr/i686-w64-mingw32
      - run: cp -r SDL2*/i686-w64-mingw32 /usr
      - run: mkdir build
      - run: cd build && cmake -DASAN=OFF -DBINARY_RELEASE=ON -DCMAKE_TOOLCHAIN_FILE=../CMake/mingwcc.cmake ..
      - run: cd build && make -j$(nproc)
      - store_artifacts: {path: ./build/devilutionx.exe, destination: devilutionx_x86.exe}

workflows:
  version: 2
  testflow:
    jobs:
      - linux_x86_64
      - linux_x86
      - windows_x86
